### ISSUE TITLE
PBS being driven by a C script

### ISSUE THREAD

**Issue by jacobseiler** [swincas/code-review#10]
I am looking to run 3 C scripts followed by a Python script iteratively over a number of snapshots.  The C scripts are parallelized and the Python script is not (the Python script just handles setting up ini files and cleaning up for the next snapshot iteration). 

Ideally I would like to have a master C script to handle running each of these other scripts via the ``system()`` command. This way I can explicitly handle the return values of each of my scripts.

However since these would all be deployed to largemem, I need to think about the correct way to request processors/memory from PBS.  For example, should it look like

```Shell
#!/bin/bash
#PBS -q largemem
#PBS -l nodes=2:ppn=32
#PBS -l walltime=01:00:00:00
#PBS -l pmem=1000gb

/Path/to/driver_script

```
And then inside the driver script have 

```C
// Loop over Snapshots // 
exit_code =  system(mpirun -np 64 /path/to/first_script first_ini.ini);
// Handle exit code //

exit_code =  system(mpirun -np 64 /path/to/second_script second_ini.ini);

// etc...
``` 
Will the driver_script be executed once and the 64 processors wait idly until they're called with the ``mpirun`` call? Do I need to deal with nasty synchronization (please no)? 

I definitely will give this implementation a shot myself but I thought I'd throw it open and see if anyone has had experiencing with executing multiple (parallel) codes within the scheduling system.

Cheers!

**Comment by manodeep** [comment]
You do not need the "exit_code" handling explicitly that way - you should be able to handle the exit codes directly from the PBS script. 


Check out the example script provided by NCI for self-submitting jobs: [here](https://opus.nci.org.au/display/Help/How+to+create+self+submitting+jobs)

**Comment by jacobseiler** [comment]
You're exactly correct.  Shell provides a way to check the exit code of the previous command with ``$?``.  The following script now correctly runs, checking the exit code of each script along the way.

```Shell
#!/bin/bash
# specify the queue name
#PBS -q sstar
# resource requests
#PBS -l nodes=1:ppn=4
#PBS -l walltime=00:20:00:00
#PBS -N self_consistent_27_60 
#PBS -l pmem=8gb

# Load Modules
module load gcc/6.4.0
module load fftw/x86_64/gnu/3.3.3-openmpi-psm
module load gsl/x86_64/gnu/1.9
module load python/x86_64/gnu/3.5.2

LowSnap=27
HighSnap=27

NUMPROC=4

for ((snap_idx = LowSnap; snap_idx < HighSnap+ 1; ++snap_idx))
{
  echo "Running Snapshot ${snap_idx}"
  mpirun -np ${NUMPROC} /path/to/first_script first_ini.ini > /path/to/log.log
  exit_code=$?
  if [ ${exit_code} -ne 0 ]; then
    echo "First code exited with errorcode ${exit_code}"
    exit ${exit_code}
  fi

  # Repeat for all other scripts.

} # Loop over snapshots.

```

Closing the issue as everything is now gucci.
