### ISSUE TITLE
Old python package is overriding newly installed version

### ISSUE THREAD

**Issue by SabineBellstedt** [swincas/code-review#11]
After updating my version of matplotlib to the most recent version, I quickly came upon the error that the most recent version of six was required for the new version of matplotlib to operate. 

The version I have installed on my machine is 1.4.1, and I required 1.10.0 or higher. I used pip to install the new version, however every time I run python, the old version is sourced. I can't use pip to uninstall the old version, so clearly past Sabine installed the older package through a non-pip mechanism. 

How can I either uninstal the old version so that it doesn't override the new version, or alternatively, point python to the path of the new one, to source it instead?

**Comment by manodeep** [comment]
Check the path for the old package with:

```python
    from __future__ import print_function
    import six
    print("Version = {0} file = {1}".format(six.__version__, six.__file__))
```
That should give you a hint as to where the package is; and how it is being resolved within your environment. 

Also, refer to the python environment code review session for a refresher: [here](https://github.com/swincas/code-review/blob/master/code-review/2017_10_27/README.rst)

**Comment by SabineBellstedt** [comment]
Is it necessary to just manually delete the file from that path, in order to fix the problem?

**Comment by SabineBellstedt** [comment]
Yep - that did the job!

**Comment by manodeep** [comment]
Yay!
