### ISSUE TITLE
Copying data between two remote computers

### ISSUE THREAD

**Issue by kgereb** [swincas/code-review#2]
I need to copy files from the Netherlands (ASTRON) to ICRAR, UWA. I have access to the ICRAR repository, and the ASTRON data is stored in an ftp server with anonymous access.

**Comment by manodeep** [comment]
This issue is solved right? Did you use `rsync --partial`?

**Comment by kgereb** [comment]
Hey Manodeep,


This is the last thing we used (with the real address censured haha):

rsync -avz --progress --partial ftp.astron.nl:bla/bla/37Pointings.tar .

Katinka

**Comment by manodeep** [comment]
Thanks! Closing this issue.
