### ISSUE TITLE
script which purges environment and load module not working

### ISSUE THREAD

**Issue by jamesesdaile** [swincas/code-review#26]
I have a script which loads various modules after deactivating environment but after running script the environment remains.

script.sh:

source deactivate
module purge
module load moog/july2014

I'm running the code with ./script.sh

**Comment by jamesesdaile** [comment]
issue resolved:  running the script with $./ has everything run as a subprocess and doesn't impact the terminal environment.  Need to run $source script.sh to have the environment affected.

**Comment by manodeep** [comment]
The solution was to `source script.sh` -- that executes everything within `script.sh` in the current shell
