### ISSUE TITLE
version clash with pip install of emcee (2.2.1) on g2

### ISSUE THREAD

**Issue by cmagoulas** [swincas/code-review#3]
I have loaded the default version of python on g2 (currently python-2.7.2) and found that it uses the old version of emcee (1.2.0). So I used pip to install emcee-2.2.1, but python will not recognise this version of it (i.e. it defaults to emcee-1.2.0).  Adding the directory (where pip installed the new version) to $PYTHONPATH does not work for importing the updated version either.

**Comment by manodeep** [comment]
Never used `emcee` on g2. May be @caitlinadams knows? 

Googling did reveal https://mail.python.org/pipermail/python-list/2009-March/526947.html - @cmagoulas can you follow the instructions and report back?

**Comment by cmagoulas** [comment]
So, I checked the $PYTHONPATH variable within Python and confirmed it was including the path to the "user" install directory (where the new emcee is), i.e. /path/to/newpackage.
But printing out "sys.path" showed it did NOT include the /path/to/newpackage.  I used sys.path.insert(1,/path/to/newpackage) to add it and when I printed out emcee.__version__ I now get "2.2.1".
This is however a pretty clunky solution!

**Comment by manodeep** [comment]
Thanks to @langmm

```python
    import site
    site.ENABLE_USER_SITE
```
should print `True`. If it prints `None`, then talk to sysadmin. If it prints `False`, then `site.main()` should add user-site directories to the front of the path.
